start:
	flask --app example --debug run --port 7000

start2:
	flask --app example2 --debug run --port 7000

start3:
	flask --app example3 --debug run --port 7000

start4:
	flask --app example4 --debug run --port 7000

start_c:
	flask --app courses --debug run --port 7000

start_f:
	flask --app forms --debug run --port 7000

start_s:
	flask --app search --debug run --port 7000

start_mf:
	flask --app modify_forms --debug run --port 7000

start_v:
	flask --app app_valid --debug run --port 7000

start_flash:
	flask --app ex_flash --debug run --port 7000

start_school:
	flask --app ex_schools --debug run --port 7000

start_posts:
	flask --app ex_posts --debug run --port 7000

start_cc:
	flask --app ex_crud_create --debug run --port 7000

start_post_cc:
	flask --app ex_post_create --debug run --port 7000

start_post_up:
	flask --app ex_posts_update --debug run --port 7000

start_cook:
	flask --app ex_cookies --debug run --port 7000

start_session:
	flask --app ex_session --debug run --port 7000

build:
	./build.sh

start_db:
	flask --app ex_db --debug run --port 7000